default:
  tags:
    - ivanov-01

stages:
  - proverka

shellcheck:
  stage: proverka
  image: koalaman/shellcheck-alpine:stable
  script:
    - echo "Вариант 01, слово labwork"
    - shellcheck --version
    - find . -name '*.sh' -print
    - find . -name '*.sh' ! -path ./work-01/commands.sh -exec shellcheck {} +
